//! The `launch_in!` / `define_module_cache!` macros and the
//! argument-conversion trait. Module-agnostic: any crate with a
//! `#[cuda_module]` block (first-party or third-party) launches through the
//! same two macros — the runtime names no kernel crate.

use crate::array::Array;
use cuda_core::{DeviceBuffer, DeviceCopy};

/// Converts a call-site argument into what the `#[cuda_module]`-generated
/// launch method expects:
///
/// | call site        | generated method takes     |
/// |------------------|----------------------------|
/// | `&Array<T>`      | `&DeviceBuffer<T>`         |
/// | `&mut Array<T>`  | `&mut DeviceBuffer<T>`     |
/// | scalar by value  | the scalar, unchanged      |
///
/// Invoked via UFCS from `launch_in!` — callers never import it explicitly.
/// Third-party crates implement it for their own by-value POD kernel params
/// (a blanket `impl<T: DeviceCopy>` is NOT possible: it conflicts with the
/// `&Array<T>` impls under coherence's future-compat rules, E0119).
pub trait AsKernelArg {
    type Out;
    #[allow(clippy::wrong_self_convention)] // deliberately consumes the reference
    fn as_karg(self) -> Self::Out;
}

impl<'a, T: DeviceCopy> AsKernelArg for &'a Array<T> {
    type Out = &'a DeviceBuffer<T>;
    #[inline(always)]
    fn as_karg(self) -> &'a DeviceBuffer<T> {
        self.__buf()
    }
}

impl<'a, T: DeviceCopy> AsKernelArg for &'a mut Array<T> {
    type Out = &'a mut DeviceBuffer<T>;
    #[inline(always)]
    fn as_karg(self) -> &'a mut DeviceBuffer<T> {
        self.__buf_mut()
    }
}

macro_rules! scalar_karg {
    ($($t:ty),* $(,)?) => {
        $(
            impl AsKernelArg for $t {
                type Out = $t;
                #[inline(always)]
                fn as_karg(self) -> $t { self }
            }
        )*
    };
}

// Primitive scalars plus shannon-core value types (kernel params by value).
// Kernel crates add their own types the same way — see `impl_kernel_arg!`.
scalar_karg!(f32, f64, i32, i64, u32, u64, usize, bool);
scalar_karg!(
    shannon_core::Vec2,
    shannon_core::Vec3,
    shannon_core::Vec4,
    shannon_core::Quat,
    shannon_core::Mat33,
);

/// Implement [`AsKernelArg`] (identity, by value) for POD types defined in
/// YOUR crate, so they can be passed to kernels by value:
///
/// ```ignore
/// shannon_rt::impl_kernel_arg!(MyParams, MyOtherParams);
/// ```
#[macro_export]
macro_rules! impl_kernel_arg {
    ($($t:ty),* $(,)?) => {
        $(
            impl $crate::AsKernelArg for $t {
                type Out = $t;
                #[inline(always)]
                fn as_karg(self) -> $t { self }
            }
        )*
    };
}

/// Define this crate's cached PTX-module accessor. Invoke ONCE at the root of
/// a kernel crate, after its `shannon_gpu_kernels!` block (which emits the
/// `kernels` module this expands against):
///
/// ```ignore
/// shannon_core::shannon_gpu_kernels! { /* rows + @raw */ }
/// shannon_rt::define_module_cache!();
/// ```
///
/// Expands to `pub fn module(&Device) -> Result<&'static kernels::LoadedModule>`
/// backed by a `OnceLock` — one cache per kernel crate, loaded on first
/// launch. The embedded-PTX lookup key is the invoking crate's package name
/// (`CARGO_PKG_NAME`), which is how several kernel crates coexist in one
/// binary.
#[macro_export]
macro_rules! define_module_cache {
    () => {
        /// Cached handle to this crate's embedded PTX module.
        /// Generated by `shannon_rt::define_module_cache!`; pass as the first
        /// argument of `shannon_rt::launch_in!`.
        pub fn module(
            dev: &$crate::Device,
        ) -> $crate::__anyhow::Result<&'static kernels::LoadedModule> {
            static MODULE: ::std::sync::OnceLock<kernels::LoadedModule> =
                ::std::sync::OnceLock::new();
            if let Some(m) = MODULE.get() {
                return Ok(m);
            }
            let m = kernels::load(dev.ctx()).map_err(|e| {
                $crate::__anyhow::anyhow!(
                    "loading embedded PTX module '{}': {e:?}",
                    env!("CARGO_PKG_NAME")
                )
            })?;
            Ok(MODULE.get_or_init(|| m))
        }
    };
}

/// Launch a kernel from a named module cache on the default device.
///
/// Resolves the module via the accessor path (first argument — typically
/// `my_kernels::module`, generated by [`define_module_cache!`]), unwraps
/// `Array` handles, and dispatches. No tape integration (record explicitly
/// via `Tape::record`) and no runtime backend selection (deferred).
///
/// Usage:  `launch_in!(my_kernels::module, affine, dim = n, (&a, scale, bias, &mut y))?;`
#[macro_export]
macro_rules! launch_in {
    ($module_fn:path, $kernel:ident, dim = $n:expr, ($($arg:expr),* $(,)?)) => {{
        (|| -> $crate::__anyhow::Result<()> {
            let __dev = $crate::Device::default()?;
            let __m = $module_fn(__dev)?;
            let __cfg = $crate::__cuda_core::LaunchConfig::for_num_elems($n as u32);
            // SAFETY: 1-D launch; the kernel guards its index against the
            // buffer length, and the caller passes buffers covering `dim`.
            unsafe { __m.$kernel(__dev.stream(), __cfg, $($crate::AsKernelArg::as_karg($arg)),*) }
                .map_err(|e| $crate::__anyhow::anyhow!(
                    "launching kernel `{}`: {e:?}", stringify!($kernel)
                ))
        })()
    }};
}
